### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by by-the-w3i** [by-the-w3i/MI-449-SS17-741-html-meta-elements-_f2DoK#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://jiangw14-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

**Comment by KatieMFritz** [comment]
Hi Wei, I'm getting a 404 error when I try to view your project at https://jiangw14-kapv98gmwdanx_f2dok.surge.sh/. Did you follow the instructions for pushing to surge? Did you get any errors in your terminal? Try to get it published, and let me or Erik know if you need help! 🙂

**Comment by by-the-w3i** [comment]
HI katie, I just fixed the issue.

**Comment by by-the-w3i** [comment]
HI @KatieMFritz  I just fixed the issue.

**Comment by KatieMFritz** [comment]
Hi Wei, getting closer! 😸 

### Unique title & description for each page
You have titles and descriptions for your pages, but the titles are vague and the descriptions describe the project, not the site itself. 

Here are some guildelines for writing titles and descriptions for your pages (including `title` and `meta name="description` elements, Twitter metadata, and Facebook (`og`) metadata:

1. **Each page should have a _unique_ title and description that describes that specific page** for people who have no idea what your site is about (because they will see this info on social media or search results before they ever come to your site). From the lesson: 

    > [It's] common for homepages to describe the entire website. On every other page however, this information should be specific to the current page.

2. **Each page should (usually) have _consistent_ titles and descriptions across platforms,** i.e. the Twitter, Open Graph, and general titles and descriptions should all match each other. This helps users figure out whether they've already visited that page. It also makes life easier for you - you can just copy and paste! Once you get into more advanced site development, you can use the same variables across all three places.

3. **Titles and descriptions should be brief.** Different platforms display different amounts of text, but I usually use [50-70 characters for titles, 100-150 characters for descriptions](http://www.thesempost.com/new-title-description-lengths-for-google-seo/). Anything longer will likely get cut off.

### Twitter
You're not using any Twitter meta tags! Look through the lesson again and add Twitter info for both pages. Please also check both pages on the [Twitter card validator](https://cards-dev.twitter.com/validator) before resubmitting.

### Facebook
I'm also getting a lot of warnings on the [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/). Please resolve all warnings for both pages, except the `fb:app_id` warning.

### Location
I see `geo.position`, but not ICBM. [From the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-meta-elements/3):
> Even though they'll provide the same information, it's good to include both of these elements, because some services might look for one, but not the other.

* * *
If you have questions about any of this, including "why does this matter??", I'm happy to chat during class or by Slack! 😁

**Comment by by-the-w3i** [comment]
Hi @KatieMFritz, I fixed these issues listed above.

**Comment by KatieMFritz** [comment]
Wei, your `title` and `meta name="description"` for both pages is great now! 🌟  The location properties are good too. 🌏 

### Facebook
You're missing Facebook data for `about.html`. On `index.html`, your title (`SEO`) doesn't describe the page, and you're missing an `og:description` property.

### Twitter
Twitter tags are missing for both pages. If you'd like, flag me down when you get to class and we can work on this together!

**Let me know when you've updated that stuff and both pages pass the Facebook AND Twitter validators.** 👍

**Comment by by-the-w3i** [comment]
Hi @KatieMFritz, finally fixed the issues, hopefully it can pass now lol

**Comment by KatieMFritz** [comment]
Nice! 🔥 

:shipit: 

FYI: For alt text, you don't have to say that it's an image; the `img` tag does that for you. 😁

**Comment by KatieMFritz** [comment]
So close now! Still missing:

- image for Twitter on `about.html`

**Comment by KatieMFritz** [comment]
Never mind - looks great! 👕 :shipit:
